const CATALOG = [
  {
    id: 1,
    type: "movie",
    title: "Dune : Deuxième Partie",
    year: 2024,
    rating: 8.2,
    genres: ["Action", "Science-Fiction"],
    duration: "2h 46min",
    synopsis: "Paul Atreides s'unit aux Fremen tout en poursuivant sa quête de vengeance contre les conspirateurs qui ont détruit sa famille. Il doit choisir entre l'amour de sa vie et le destin de l'univers connu.",
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Austin Butler"],
    poster: "https://media.themoviedb.org/t/p/w500/6izwz7rsy95ARzTR3poZ8H6c5pp.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Dune-Deuxieme-Partie/S01/dune-deuxieme-partie-S01-E01.mp4?ff=1789274584.umzAzE-5MStby9uDisTFKYm9",
    featured: true
  },
  {
    id: 2,
    type: "movie",
    title: "Oppenheimer",
    year: 2023,
    rating: 8.5,
    genres: ["Drame", "Histoire"],
    duration: "3h 00min",
    synopsis: "L'histoire du rôle de J. Robert Oppenheimer dans le développement de la bombe atomique pendant la Seconde Guerre mondiale.",
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
    poster: "https://media.themoviedb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Oppenheimer/S01/oppenheimer-S01-E01.mp4?ff=1789274664.3BogItpwQ2rIE-UTrFq8SSkT"
  },
  {
    id: 3,
    type: "movie",
    title: "Deadpool & Wolverine",
    year: 2024,
    rating: 7.7,
    genres: ["Action", "Comédie"],
    duration: "2h 08min",
    synopsis: "Wade Wilson doit reprendre son costume quand une menace pèse sur son monde. Il recrute un Wolverine réticent pour une mission qui changera l'histoire du MCU.",
    director: "Shawn Levy",
    cast: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin"],
    poster: "https://media.themoviedb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Deadpool-Wolverine/S01/deadpool-wolverine-S01-E01.mp4?ff=1789274717.jvsHze4yW9Gdb3fbHaIJjvVJ"
  },
  {
    id: 4,
    type: "movie",
    title: "Gladiator II",
    year: 2024,
    rating: 6.8,
    genres: ["Action", "Drame"],
    duration: "2h 28min",
    synopsis: "Lucius, forcé d'entrer dans le Colisée après la conquête de sa patrie, doit puiser dans son passé pour retrouver force et honneur et redonner gloire à Rome.",
    director: "Ridley Scott",
    cast: ["Paul Mescal", "Denzel Washington", "Pedro Pascal"],
    poster: "https://media.themoviedb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Gladiator-Ii/S01/gladiator-ii-S01-E01.mp4?ff=1789274756.TD7pWKDmmV3Kz8dmCGvDEFIM"
  },
  {
    id: 5,
    type: "movie",
    title: "Top Gun : Maverick",
    year: 2022,
    rating: 8.2,
    genres: ["Action", "Drame"],
    duration: "2h 11min",
    synopsis: "Après plus de trente ans de service, Pete \"Maverick\" Mitchell forme une troupe de diplômés du Top Gun pour une mission sans précédent que jamais aucun pilote n'a vue.",
    director: "Joseph Kosinski",
    cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly"],
    poster: "https://media.themoviedb.org/t/p/w500/n0YuM4f5lvGAP6MAW2kBIzugXnc.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Top-Gun-Maverick/S01/top-gun-maverick-S01-E01.mp4?ff=1789274817.7dMAxPnCWNMPTRkjIp8fVAs8"
  },
  {
    id: 6,
    type: "movie",
    title: "The Batman",
    year: 2022,
    rating: 7.8,
    genres: ["Action", "Policier"],
    duration: "2h 56min",
    synopsis: "Dans sa deuxième année de lutte contre le crime, Batman découvre la corruption à Gotham qui relie sa propre famille tout en affrontant le Riddler.",
    director: "Matt Reeves",
    cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano"],
    poster: "https://media.themoviedb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/The-Batman-2022/S01/the-batman-2022-S01-E01.mp4?ff=1789274848.OLH27tVb4RJ06ci2X_4Zm0mZ"
  },
  {
    id: 7,
    type: "movie",
    title: "Barbie",
    year: 2023,
    rating: 6.8,
    genres: ["Comédie", "Fantaisie"],
    duration: "1h 54min",
    synopsis: "Barbie et Ken vivent le temps de leur vie dans le monde parfait de Barbie Land. Quand elles découvrent le monde réel, tout change.",
    director: "Greta Gerwig",
    cast: ["Margot Robbie", "Ryan Gosling", "America Ferrera"],
    poster: "https://media.themoviedb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    source: "https://cdn78.vida-loka.store/movies/Barbie-2023.mp4?ff=1789274881.i4nuXLyvRu0CO2l0emA2Tac1"
  }
];