const CATALOG = [
  {
    id: 1,
    type: "movie",
    title: "Dune : Deuxième Partie",
    year: 2024,
    rating: 8.2,
    genres: ["Action", "Science-Fiction"],
    duration: "2h 46min",
    synopsis: "Paul Atreides s'unit aux Fremen tout en poursuivant sa quête de vengeance contre les conspirateurs qui ont détruit sa famille. Il doit choisir entre l'amour de sa vie et le destin de l'univers connu.",
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Austin Butler"],
    poster: "https://media.themoviedb.org/t/p/w500/6izwz7rsy95ARzTR3poZ8H6c5pp.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Dune-Deuxieme-Partie/S01/dune-deuxieme-partie-S01-E01.mp4?ff=1789274584.umzAzE-5MStby9uDisTFKYm9",
    featured: true
  },
  {
    id: 2,
    type: "movie",
    title: "Oppenheimer",
    year: 2023,
    rating: 8.5,
    genres: ["Drame", "Histoire"],
    duration: "3h 00min",
    synopsis: "L'histoire du rôle de J. Robert Oppenheimer dans le développement de la bombe atomique pendant la Seconde Guerre mondiale.",
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
    poster: "https://media.themoviedb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Oppenheimer/S01/oppenheimer-S01-E01.mp4?ff=1789274664.3BogItpwQ2rIE-UTrFq8SSkT"
  },
  {
    id: 3,
    type: "movie",
    title: "Deadpool & Wolverine",
    year: 2024,
    rating: 7.7,
    genres: ["Action", "Comédie"],
    duration: "2h 08min",
    synopsis: "Wade Wilson doit reprendre son costume quand une menace pèse sur son monde. Il recrute un Wolverine réticent pour une mission qui changera l'histoire du MCU.",
    director: "Shawn Levy",
    cast: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin"],
    poster: "https://media.themoviedb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Deadpool-Wolverine/S01/deadpool-wolverine-S01-E01.mp4?ff=1789274717.jvsHze4yW9Gdb3fbHaIJjvVJ"
  },
  {
    id: 4,
    type: "movie",
    title: "Gladiator II",
    year: 2024,
    rating: 6.8,
    genres: ["Action", "Drame"],
    duration: "2h 28min",
    synopsis: "Lucius, forcé d'entrer dans le Colisée après la conquête de sa patrie, doit puiser dans son passé pour retrouver force et honneur et redonner gloire à Rome.",
    director: "Ridley Scott",
    cast: ["Paul Mescal", "Denzel Washington", "Pedro Pascal"],
    poster: "https://media.themoviedb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Gladiator-Ii/S01/gladiator-ii-S01-E01.mp4?ff=1789274756.TD7pWKDmmV3Kz8dmCGvDEFIM"
  },
  {
    id: 5,
    type: "movie",
    title: "Top Gun : Maverick",
    year: 2022,
    rating: 8.2,
    genres: ["Action", "Drame"],
    duration: "2h 11min",
    synopsis: "Après plus de trente ans de service, Pete \"Maverick\" Mitchell forme une troupe de diplômés du Top Gun pour une mission sans précédent que jamais aucun pilote n'a vue.",
    director: "Joseph Kosinski",
    cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly"],
    poster: "https://media.themoviedb.org/t/p/w500/n0YuM4f5lvGAP6MAW2kBIzugXnc.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Top-Gun-Maverick/S01/top-gun-maverick-S01-E01.mp4?ff=1789274817.7dMAxPnCWNMPTRkjIp8fVAs8"
  },
  {
    id: 6,
    type: "movie",
    title: "The Batman",
    year: 2022,
    rating: 7.8,
    genres: ["Action", "Policier"],
    duration: "2h 56min",
    synopsis: "Dans sa deuxième année de lutte contre le crime, Batman découvre la corruption à Gotham qui relie sa propre famille tout en affrontant le Riddler.",
    director: "Matt Reeves",
    cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano"],
    poster: "https://media.themoviedb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/The-Batman-2022/S01/the-batman-2022-S01-E01.mp4?ff=1789274848.OLH27tVb4RJ06ci2X_4Zm0mZ"
  },
  {
    id: 7,
    type: "movie",
    title: "Barbie",
    year: 2023,
    rating: 6.8,
    genres: ["Comédie", "Aventure"],
    duration: "1h 54min",
    synopsis: "Barbie et Ken vivent le temps de leur vie dans le monde parfait de Barbie Land. Quand elles découvrent le monde réel, tout change.",
    director: "Greta Gerwig",
    cast: ["Margot Robbie", "Ryan Gosling", "America Ferrera"],
    poster: "https://media.themoviedb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    source: "https://cdn78.vida-loka.store/movies/Barbie-2023.mp4?ff=1789274881.i4nuXLyvRu0CO2l0emA2Tac1"
  },
  /* ===== films ajoutés — colle ton lien dans "source" de chaque film ===== */
  {
    id: 8,
    type: "movie",
    title: "Avatar : La Voie de l'eau",
    year: 2022,
    rating: 7.6,
    genres: ["Action", "Science-Fiction"],
    duration: "3h 12min",
    synopsis: "Jake Sully vit désormais avec sa famille sur Pandora. Une nouvelle menace les force à quitter leur foyer et à explorer les régions marines de la planète.",
    director: "James Cameron",
    cast: ["Sam Worthington", "Zoe Saldaña", "Sigourney Weaver"],
    poster: "https://media.themoviedb.org/t/p/w500/7TOaaKbSYfilIpZsRCS1AyFCxaJ.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Avatar-La-Voie-De-L-Eau/S01/avatar-la-voie-de-l-eau-S01-E01.mp4?ff=1789333201.-k8V0tD2gH-LtiPJ6wLdUCVh"
  },
  {
    id: 9,
    type: "movie",
    title: "Spider-Man : No Way Home",
    year: 2021,
    rating: 8.0,
    genres: ["Action", "Science-Fiction"],
    duration: "2h 28min",
    synopsis: "L'identité secrète de Peter Parker est révélée au monde entier. Désespéré, il demande de l'aide au docteur Strange, mais quelque chose tourne mal.",
    director: "Jon Watts",
    cast: ["Tom Holland", "Zendaya", "Benedict Cumberbatch"],
    poster: "https://media.themoviedb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Spider-Man-No-Way-Home/S01/spider-man-no-way-home-S01-E01.mp4?ff=1789333248.SwX_N4WHHHq88A_Kv5vtajiL"
  },
  {
    id: 10,
    type: "movie",
    title: "Interstellar",
    year: 2014,
    rating: 8.7,
    genres: ["Drame", "Science-Fiction"],
    duration: "2h 49min",
    synopsis: "Alors que la Terre se meurt, un groupe d'explorateurs franchit un trou de ver pour trouver un nouveau refuge à l'humanité au-delà des étoiles.",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    poster: "https://media.themoviedb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Interstellar/S01/interstellar-S01-E01.mp4?ff=1789333287.Y8GorwjZ3fOYa2-i1XYd_Rcz"
  },
  {
    id: 11,
    type: "movie",
    title: "Avengers : Endgame",
    year: 2019,
    rating: 8.1,
    genres: ["Action", "Science-Fiction"],
    duration: "3h 01min",
    synopsis: "Les Avengers rescapés tentent l'impossible pour ramener ceux qui ont été anéantis par Thanos. Des choix décisifs changeront leur destin à jamais.",
    director: "Anthony et Joe Russo",
    cast: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
    poster: "https://media.themoviedb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Avengers-Endgame/S01/avengers-endgame-S01-E01.mp4?ff=1789333343.8V0EXxevmlbEwraLCccsxmCA"
  },
  {
    id: 12,
    type: "movie",
    title: "John Wick : Chapitre 4",
    year: 2023,
    rating: 7.7,
    genres: ["Action", "Policier"],
    duration: "2h 49min",
    synopsis: "John Wick découvre comment vaincre la Grande Table. Mais avant de gagner sa liberté, il doit affronter un nouvel ennemi plus puissant que jamais.",
    director: "Chad Stahelski",
    cast: ["Keanu Reeves", "Donnie Yen", "Bill Skarsgård"],
    poster: "https://media.themoviedb.org/t/p/w500/n1YTIyhAqqqFyDGFTzV7WaU1JfK.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/John-Wick-Chapitre-4/S01/john-wick-chapitre-4-S01-E01.mp4?ff=1789333390.Kin-_mrVhgX7-HVt_9vGFnlK"
  },
  {
    id: 13,
    type: "movie",
    title: "The Dark Knight : Le Chevalier noir",
    year: 2008,
    rating: 9.0,
    genres: ["Action", "Policier"],
    duration: "2h 32min",
    synopsis: "Batman affronte le Joker, un criminel qui plonge Gotham dans le chaos et pousse les héros à leurs limites morales.",
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    poster: "https://media.themoviedb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Batman-The-Dark-Knight-Lechevalier-Noir/S01/Batman-The-Dark-Knight-Le-Chevalier-noir-S01-E01.mp4?ff=1789333431.WUXxVHFEiKq7p5qszHeS0gHy"
  },
  {
    id: 14,
    type: "movie",
    title: "Inception",
    year: 2010,
    rating: 8.8,
    genres: ["Action", "Science-Fiction"],
    duration: "2h 28min",
    synopsis: "Dom Cobb vole des secrets en s'infiltrant dans les rêves. On lui propose une dernière mission impossible : implanter une idée dans l'esprit d'une cible.",
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Tom Hardy"],
    poster: "https://media.themoviedb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Inception/S01/Inception-S01-E01.mp4?ff=1789333502.C-_4AR6fleOqdkG8cgXy2MW3"
  },
  {
    id: 15,
    type: "movie",
    title: "Le Parrain",
    year: 1972,
    rating: 9.2,
    genres: ["Policier", "Drame"],
    duration: "2h 55min",
    synopsis: "La saga de la famille Corleone, entre traditions mafieuses, loyauté et trahison, à travers le destin du jeune Michael.",
    director: "Francis Ford Coppola",
    cast: ["Marlon Brando", "Al Pacino", "James Caan"],
    poster: "https://media.themoviedb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    source: "https://cdn78.vida-loka.store/movies/Le-Parrain-1972.mp4?ff=1789333534.CmvUDQxFIGLHujJEmdI6oVOo"
  },
  {
    id: 16,
    type: "movie",
    title: "Spider-Man : Brand New Day",
    year: 2026,
    rating: 8.5,
    genres: ["Action", "Science-Fiction"],
    duration: "2h 30min",
    synopsis: "Quatre ans se sont écoulés, Peter, désormais adulte, vit seul, s'est volontairement effacé de la vie et des souvenirs de ses proches. Luttant contre le crime dans un New York qui ne le reconnaît plus, il se consacre entièrement à la protection de la ville - un Spider-Man à plein temps - mais à mesure que les responsabilités s'intensifient, la pression provoque une transformation physique surprenante qui menace son existence, tandis qu'une étrange nouvelle vague de crimes donne naissance à l'une des menaces les plus redoutables qu'il ait jamais affrontées.",
    director: "Destin Daniel Cretton",
    cast: ["Tom Holland", "Zendaya", "Jon Bernthal"],
    poster: "https://media.themoviedb.org/t/p/w500/hdYqHWsKvrzfbdDNrKdrCMWJ0H0.jpg",
    source: "https://cdn78.vida-loka.store/movies/Spider-Man-Brand-New-Day-2026-Swiftflow.mp4?ff=1789333700.SRBxD6uGds03LYPpS3ZTcIcV"
  },
  {
    id: 17,
    type: "movie",
    title: "Matrix",
    year: 1999,
    rating: 8.7,
    genres: ["Science-Fiction", "Action"],
    duration: "2h 16min",
    synopsis: "Neo découvre que le monde qu'il connaît est une simulation et rejoint la résistance humaine contre les machines.",
    director: "Les Wachowski",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    poster: "https://media.themoviedb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Matrix/S01/matrix-S01-E01.mp4?ff=1789333738.nQ7GmwfyAxM1hZpGs3XuhH_2"
  },
  {
    id: 18,
    type: "movie",
    title: "Black Panther : Wakanda Forever",
    year: 2022,
    rating: 6.6,
    genres: ["Action", "Science-Fiction"],
    duration: "2h 41min",
    synopsis: "Shuri doit protéger Wakanda alors que le monde découvre le vibranium et qu'une nouvelle nation sous-marine menace de tout dévaster.",
    director: "Ryan Coogler",
    cast: ["Letitia Wright", "Danai Gurira", "Tenoch Huerta"],
    poster: "https://media.themoviedb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    source: "https://cdn78.vida-loka.store/movies/Black-Panther-Wakanda-Forever-2022.mp4?ff=1789333780.QkMrRpEKR5haYmvwO3ymUeE9"
  },
  {
    id: 19,
    type: "movie",
    title: "Everything Everywhere All at Once",
    year: 2022,
    rating: 8.1,
    genres: ["Science-Fiction", "Comédie"],
    duration: "2h 19min",
    synopsis: "Une laverie prise dans une crise dimensionnelle : Evelyn doit sauver le multivers tout en gérant sa vie familiale chaotique.",
    director: "Daniel Kwan et Daniel Scheinert",
    cast: ["Michelle Yeoh", "Ke Huy Quan", "Stephanie Hsu"],
    poster: "https://media.themoviedb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    source: "https://cdn78.vida-loka.store/movies/Everything-Everywhere-All-at-Once.mp4?ff=1789333821.SGmQgO5jjqYHvwUavAtrKjCN"
  },
  
  {
    id: 21,
    type: "movie",
    title: "Conjuring : Les Dossiers Warren",
    year: 2013,
    rating: 7.5,
    genres: ["Horreur", "Thriller"],
    duration: "1h 52min",
    synopsis: "En 1971, les enquêteurs paranormaux Ed et Lorraine Warren viennent en aide à une famille terrorisée par une présence sombre dans leur ferme du Rhode Island.",
    director: "James Wan",
    cast: ["Vera Farmiga", "Patrick Wilson", "Lili Taylor"],
    poster: "https://media.themoviedb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Conjuring-Les-Dossiers-Warren/S01/conjuring-les-dossiers-warren-S01-E01.mp4?ff=1789348965.tBiAip0nuIiVQTlcIhc44POT"
  },
  {
    id: 22,
    type: "movie",
    title: "Hérédité",
    year: 2018,
    rating: 7.3,
    genres: ["Horreur", "Drame"],
    duration: "2h 07min",
    synopsis: "Après la mort de sa mère secrète, une femme découvre des secrets terrifiants sur son héritage familial et doit affronter un destin sinistre.",
    director: "Ari Aster",
    cast: ["Toni Collette", "Alex Wolff", "Milly Shapiro"],
    poster: "https://media.senscritique.com/media/000021637753/300/heredite.png",
    source: "https://cdn78.vida-loka.store/movies/Heredite.mp4?ff=1789349006.vp5NeTx3G0tFgp9D8JyGLKHp"
  },
  {
    id: 23,
    type: "movie",
    title: "Smile",
    year: 2022,
    rating: 6.5,
    genres: ["Horreur", "Thriller"],
    duration: "1h 55min",
    synopsis: "Après avoir été témoin d'un incident traumatisant, une psychiatre se met à vivre des expériences terrifiantes qu'elle ne peut pas expliquer.",
    director: "Parker Finn",
    cast: ["Sosie Bacon", "Jessie T. Usher", "Kyle Gallner"],
    poster: "https://images3.cinefil.com/movies/1124687.webp?class=og",
    source: "https://cdn78.vida-loka.store/series/VF/Smile-1/S01/smile-1-S01-E01.mp4?ff=1789349051.dCdbmO1HAan_cu0hnVV6GDmA"
  },
  {
    id: 24,
    type: "movie",
    title: "La Nonne",
    year: 2018,
    rating: 5.3,
    genres: ["Horreur", "Thriller"],
    duration: "1h 36min",
    synopsis: "Un prêtre et une novice sont envoyés par le Vatican pour enquêter sur la mort mystérieuse d'une nonne en Roumanie, où ils affrontent une force démoniaque.",
    director: "Corin Hardy",
    cast: ["Taissa Farmiga", "Demián Bichir", "Jonas Bloquet"],
    poster: "https://images3.cinefil.com/movies/1144136.webp?class=og",
    source: "https://cdn78.vida-loka.store/series/VF/La-Nonne/S01/la-nonne-S01-E01.mp4?ff=1789349095.Eabe4Hkx1VvZ5KSq77PK7s2a"
  },

  /* ===== ANIME MOVIES ===== */
  {
    id: 26,
    type: "movie",
    title: "Your Name (Kimi no Na wa)",
    year: 2016,
    rating: 8.4,
    genres: ["Anime", "Romance", "Drame"],
    duration: "1h 46min",
    synopsis: "Deux lycéens, Mitsuha à la campagne et Taki à Tokyo, commencent à échanger leurs corps dans leurs rêves. Une connexion mystique les unit à travers le temps et l'espace.",
    director: "Makoto Shinkai",
    cast: ["Ryunosuke Kamiki", "Mone Kamishiraishi", "Ryo Narita"],
    poster: "https://images.affiches-et-posters.com//albums/3/68249/medium/affiche-film-your-name.jpg",
    source: "https://cdn78.vida-loka.store/movies/Your-Name.mp4?ff=1789349424.zvFsiNoFsBn5nu_-sLNv3xrC"
  },
  {
    id: 27,
    type: "movie",
    title: "Spider-Man",
    year: 2002,
    rating: 7.3,
    genres: ["Action", "Aventure", "Science-Fiction"],
    duration: "2h 01min",
    synopsis: "Orphelin, Peter Parker, lycéen timide et brillant, est mordu par une araignée génétiquement modifiée et développe des pouvoirs surhumains. Sous le costume de Spider-Man, il doit concilier sa vie de lycéen avec sa nouvelle mission de super-héros face au Bouffon Vert.",
    director: "Sam Raimi",
    cast: ["Tobey Maguire", "Willem Dafoe", "Kirsten Dunst"],
    poster: "https://upload.wikimedia.org/wikipedia/en/6/6c/Spider-Man_%282002_film%29_poster.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Spider-Man-1/S01/Spider-Man-1-S01-E01.mp4?ff=1789516369.r5StmJwCC7lg8aRjdYKp7nI-"
  },
  {
    id: 36,
    type: "movie",
    title: "Spider-Man 2",
    year: 2004,
    rating: 7.3,
    genres: ["Action", "Aventure", "Science-Fiction"],
    duration: "2h 07min",
    synopsis: "Deux ans plus tard, Peter Parker cherche à concilier sa vie d'étudiant et ses exploits en costume. Le docteur Octopus, scientifique tragiquement transformé, menace New York, et Spider-Man devra faire le choix déchirant entre être un héros et être heureux.",
    director: "Sam Raimi",
    cast: ["Tobey Maguire", "Alfred Molina", "Kirsten Dunst"],
    poster: "https://upload.wikimedia.org/wikipedia/en/4/4e/Spider-Man_2_USA_poster.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Spider-Man-2/S01/spider-man-2-S01-E01.mp4?ff=1789516419.FFMiSHUOu4-orDsVGYfQF3ue"
  },
  {
    id: 37,
    type: "movie",
    title: "Spider-Man 3",
    year: 2007,
    rating: 6.2,
    genres: ["Action", "Aventure", "Fantastique"],
    duration: "2h 20min",
    synopsis: "Peter Parker voit sa vie bouleversée quand un symbiote extraterrestre se fixe sur son costume, décuplant sa puissance mais révélant son côté sombre. Face à Venom, au sable de l'Homme-Sable et à son ancien ami Harry Osborn, il devra lutter contre ce qu'il a de plus noir en lui.",
    director: "Sam Raimi",
    cast: ["Tobey Maguire", "Topher Grace", "James Franco"],
    poster: "https://upload.wikimedia.org/wikipedia/en/7/7a/Spider-Man_3%2C_International_Poster.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Spider-Man-3/S01/Spider-Man-3-S01-E01.mp4?ff=1789516470.VDJ2iaW1vRaQH6Hils0GFgmA"
  },
  {
    id: 28,
    type: "movie",
    title: "Suzume (Suzume no Tojimari)",
    year: 2022,
    rating: 7.7,
    genres: ["Anime", "Aventure"],
    duration: "2h 02min",
    synopsis: "Suzume, 17 ans, découvre une porte mystérieuse qui ouvre sur des ruines. Elle doit refermer les portes qui apparaissent à travers le Japon pour éviter des catastrophes.",
    director: "Makoto Shinkai",
    cast: ["Nanoka Hara", "Hokuto Matsumura", "Eri Fukatsu"],
    poster: "https://m.media-amazon.com/images/I/91mS9pS8NnL._AC_SY741_.jpg",
    source: "https://cdn78.vida-loka.store/movies/suzume-2022.mp4?ff=1789349531.yKwsElmA20jdiwxx7vwdBav2"
  },
  {
    id: 29,
    type: "movie",
    title: "A Silent Voice (Koe no Katachi)",
    year: 2016,
    rating: 8.1,
    genres: ["Anime", "Drame"],
    duration: "2h 10min",
    synopsis: "Un ancien harceleur cherche la rédemption en retrouvant la fille sourde qu'il a maltraitée. Une histoire touchante sur le pardon, l'amitié et la réconciliation.",
    director: "Naoko Yamada",
    cast: ["Miyu Irino", "Saori Hayami", "Aoi Yuki"],
    poster: "https://cdn.posteritati.com/posters/000/000/075/119/a-silent-voice-the-movie-md-web.jpg",
    source: "https://cdn78.vida-loka.store/movies/Silent-Voice-2016-Naoko-Yamada.mp4?ff=1789349563.bujbmQemxwH97MAbf_tI-CxE"
},
  {

    id: 31,
    type: "movie",
    title: "Princess Mononoke",
    year: 1997,
    rating: 8.4,
    genres: ["Anime", "Aventure", "Fantastique"],
    duration: "2h 14min",
    synopsis: "Le prince Ashitaka, maudit par un dieu-démon, cherche un remède. Il se retrouve au cœur du conflit entre les humains déforestant la forêt et les dieux-animaux.",
    director: "Hayao Miyazaki",
    cast: ["Yoji Matsuda", "Yuriko Ishida", "Yuko Tanaka"],
    poster: "https://m.media-amazon.com/images/I/512WcFaKaKL._AC_.jpg",
    source: "https://cdn78.vida-loka.store/movies/Princesse-Mononoke.mp4?ff=1789349692.Gi7yMgErtYD0wdrMCYHHOxVu"
  },
  {
    id: 32,
    type: "movie",
    title: "Howl's Moving Castle (Le Château dans le ciel)",
    year: 2004,
    rating: 8.2,
    genres: ["Anime", "Aventure", "Fantastique"],
    duration: "1h 59min",
    synopsis: "Sophie, transformée en vieille femme par une sorcière, trouve refuge dans le château ambulant du magicien Howl. Une aventure magique entre guerre et sorts.",
    director: "Hayao Miyazaki",
    cast: ["Chieko Baisho", "Takuya Kimura", "Akihiro Miwa"],
    poster: "https://m.media-amazon.com/images/I/61SV8zbLMPL._AC_.jpg",
    source: "https://cdn78.vida-loka.store/movies/le-chateau-dans-le-ciel.mp4?ff=1789349647.1x8fXbtPC0_9aZY71qfJm7CF"
  },
  {
    id: 33,
    type: "movie",
    title: "Demon Slayer: Mugen Train",
    year: 2020,
    rating: 7.7,
    genres: ["Anime", "Action", "Aventure"],
    duration: "1h 57min",
    synopsis: "Tanjiro et ses amis montent dans le Train de l'Infini pour enquêter sur des disparitions. Ils affrontent un démon de rang supérieur qui manipule les rêves.",
    director: "Haruo Sotozaki",
    cast: ["Natsuki Hanae", "Akari Kito", "Hiro Shimono"],
    poster: "https://i.pinimg.com/736x/cf/1e/8b/cf1e8b87bd9796167da4acfbc5ad2ac3.jpg",
    source: "https://cdn78.vida-loka.store/movies/Demon-Slayer-Kimetsu-No-Yaiba-Le-Film-La-Forteresse-Infinie-2025.mp4?ff=1789349752.LGbzMv_bmQuTaKdWkhUGOqQ7"
  },
  {
    id: 34,
    type: "movie",
    title: "Jujutsu Kaisen 0",
    year: 2021,
    rating: 7.8,
    genres: ["Anime", "Action"],
    duration: "1h 45min",
    synopsis: "Yuta Okkotsu, hanté par l'esprit de son amie d'enfance, rejoint l'école d'exorcisme de Tokyo Jujutsu High pour apprendre à contrôler son pouvoir maudit.",
    director: "Sunghoo Park",
    cast: ["Megumi Ogata", "Kana Hanazawa", "Takako Honda"],
    poster: "https://image.tmdb.org/t/p/original/jW4OW6ySAtP40BzUWgVmsApqyaS.jpg",
    source: "https://cdn78.vida-loka.store/series/VF/Jujutsu-Kaisen-0/S01/Jujutsu-Kaisen-0-S01-E01.mp4?ff=1789349776.45XjOs7trIVW-M269lLlhhaJ"
  },
  {
    id: 35,
    type: "movie",
    title: "The Boy and the Heron (Kimitachi wa Dou Ikiru ka)",
    year: 2023,
    rating: 7.5,
    genres: ["Anime", "Aventure", "Fantastique"],
    duration: "2h 04min",
    synopsis: "Après la mort de sa mère, Mahito emménage avec sa belle-mère dans une tour où un héron gris l'entraîne dans un monde fantastique entre vie et mort.",
    director: "Hayao Miyazaki",
    cast: ["Soma Santoki", "Masaki Suda", "Ko Shibasaki"],
    poster: "https://static0.colliderimages.com/wordpress/wp-content/uploads/2023/10/the-boy-and-the-heron-poster.jpeg",
    source: "https://cdn78.vida-loka.store/movies/le-garcon-et-le-heron.mp4?ff=1789349647.1x8fXbtPC0_9aZY71qfJm7CF"
  }
];